title: Leemsmid
slogan: "**Pretty leem!**"
color_accent: "#c5d9bc"
color_dark: "#163d26"
color_light: "#fefefe"
lab: In het leemlab houd ik je op de hoogte van verschillende experimenten om
  het leemproduct nog te verbeteren, beide in constructieve integriteit en
  estetisch.
about_text: >-
  Mijn naam is Tom Smit en ik heb als doel om de reguliere bouw ecologischer in
  te richten en dat toegankelijk te maken voor iedere klant. Het is een
  prachtige manier om te werken met natuurlijke materialen die fantastisch
  inzetbaar zijn aan de binnen en buitenkant van uw huis. Ik ben gediplomeerd
  stukadoor in conventionele materialen (gips en cement) en ik heb mij daarna
  gespecialiseerd in de natuurlijke materialen (leem). Ik sta achter deze
  materialen omdat wanneer we de keuze hebben en we voor een gezondere keuze
  kiezen, we onze eigen steen bijdragen aan een betere toekomst.




  De materialen die ik verwerk zijn altijd damp open, dit zorgt dat het huis kan blijven 'ademen' en met een eindafwerking als leem zorg je dat er altijd een stabiel binnenhuis klimaat is waardoor dit prettiger voelt om in te leven.


  Ambachtelijke materialen




  Visie beknopt tom smit


  Verdere missie ergens anders lezen
about_image: /assets/img_7011.jpg
footer_image: /assets/footer.jpg
phone: 06 5194 7969
email: info@leemsmid.nl
instagram: wilmavis
instagram_feed: uMytQGrvbKV1c5Vn
contact: >-
  ### **Leemsmid**


  Wilt u meer weten over ecologisch renoveren? Heeft u een muur of een huis dat leemstuc kan gebruiken? Bel gerust. Ik kom graag langs om te kijken wat allemaal mogelijk is en voorlichting te geven over deze producten.


  * **BTW** NL002225479B98

  * **KVK** 74691740
repository: danielbeeke/leemsmid
sass:
  sass_dir: _sass
url: https://leemsmid.danielbeeke.nl
collections:
  blocks:
    sort_by: weight
  faq: null
  showcases:
    output: true
  experiments: null
menu_image: https://afresco.be/wp/wp-content/gallery/leem/leem-008_43.jpg
description: Leemsmid
baseurl: ""
